// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xomrrxxydfvjwwpccrpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvbXJyeHh5ZGZ2and3cGNjcnBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTA5MjUsImV4cCI6MjA3Mjg4NjkyNX0.nJRHh9TbYr6q9fkTe6XWsI3-x6KELVnvmNF7cmMZOW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});